/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClassBooking = IDL.Record({
  'userName' : IDL.Text,
  'userEmail' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'className' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const FreeTrialSignup = IDL.Record({
  'goal' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'bookClass' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'freeTrial' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllClassBookings' : IDL.Func([], [IDL.Vec(ClassBooking)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getAllFreeTrials' : IDL.Func([], [IDL.Vec(FreeTrialSignup)], ['query']),
  'getAllNewsletterSignups' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'signupNewsletter' : IDL.Func([IDL.Text], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClassBooking = IDL.Record({
    'userName' : IDL.Text,
    'userEmail' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'className' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FreeTrialSignup = IDL.Record({
    'goal' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'bookClass' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'freeTrial' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllClassBookings' : IDL.Func([], [IDL.Vec(ClassBooking)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getAllFreeTrials' : IDL.Func([], [IDL.Vec(FreeTrialSignup)], ['query']),
    'getAllNewsletterSignups' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'signupNewsletter' : IDL.Func([IDL.Text], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };